[[constraint]]
  name = "github.com/jawher/mow.cli"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-isatty"

[[constraint]]
  branch = "master"
  name = "github.com/imdario/mergo"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/genuinetools/reg"
  version = "0.16.0"

[[constraint]]
  name = "github.com/manifoldco/promptui"
  version = "0.3.2"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  revision = "3b9e5d653ede77b578819b587537227c1ac9f487"

[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  version = "1.6.0"
