[[constraint]]
  name = "github.com/jawher/mow.cli"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-isatty"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"
 
[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0"

# Required to use client-go with dep, see https://github.com/kubernetes/client-go/blob/master/INSTALL.md

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "58f6f26e200fa5dfb40c9cd1c83f3e2c860d779d"

[[override]]
  name = "github.com/PuerkitoBio/purell"
  revision = "8a290539e2e8629dbc4e6bad948158f790ec31f4"

[[override]]
  name = "github.com/PuerkitoBio/urlesc"
  revision = "5bd2802263f21d8788851d5305584c82a5c75d7e"

[[override]]
  name = "github.com/coreos/go-oidc"
  revision = "a4973d9a4225417aecf5d450a9522f00c1f7130f"

[[override]]
  name = "github.com/coreos/pkg"
  revision = "fa29b1d70f0beaddd4c7021607cc3c3be8ce94b8"

[[override]]
  name = "github.com/davecgh/go-spew"
  revision = "5215b55f46b2b919f50a1df0eaa5886afe4e3b3d"

[[override]]
  name = "github.com/dgrijalva/jwt-go"
  revision = "01aeca54ebda6e0fbfafd0a524d234159c05ec20"

[[override]]
  name = "github.com/docker/distribution"
  revision = "cd27f179f2c10c5d300e6d09025b538c475b0d51"

[[override]]
  name = "github.com/docker/spdystream"
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"

[[override]]
  name = "github.com/emicklei/go-restful"
  revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"

[[override]]
  name = "github.com/emicklei/go-restful-swagger12"
  revision = "dcef7f55730566d41eae5db10e7d6981829720f6"

[[override]]
  name = "github.com/ghodss/yaml"
  revision = "73d445a93680fa1a78ae23a5839bad48f32ba1ee"

[[override]]
  name = "github.com/go-openapi/analysis"
  revision = "b44dc874b601d9e4e2f6e19140e794ba24bead3b"

[[override]]
  name = "github.com/go-openapi/jsonpointer"
  revision = "46af16f9f7b149af66e5d1bd010e3574dc06de98"

[[override]]
  name = "github.com/go-openapi/jsonreference"
  revision = "13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272"

[[override]]
  name = "github.com/go-openapi/loads"
  revision = "18441dfa706d924a39a030ee2c3b1d8d81917b38"

[[override]]
  name = "github.com/go-openapi/spec"
  revision = "6aced65f8501fe1217321abf0749d354824ba2ff"

[[override]]
  name = "github.com/go-openapi/swag"
  revision = "1d0bd113de87027671077d3c71eb3ac5d7dbba72"

[[override]]
  name = "github.com/gogo/protobuf"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"

[[override]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[override]]
  name = "github.com/golang/groupcache"
  revision = "02826c3e79038b59d737d3b1c0a1d937f71a4433"

[[override]]
  name = "github.com/golang/protobuf"
  revision = "4bd1920723d7b7c925de087aa32e2187708897f7"

[[override]]
  name = "github.com/google/gofuzz"
  revision = "44d81051d367757e1c7c6a5a86423ece9afcf63c"

[[override]]
  name = "github.com/hashicorp/golang-lru"
  revision = "a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4"

[[override]]
  name = "github.com/howeyc/gopass"
  revision = "bf9dde6d0d2c004a008c27aaee91170c786f6db8"

[[override]]
  name = "github.com/imdario/mergo"
  revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"

[[override]]
  name = "github.com/jonboulle/clockwork"
  revision = "72f9bd7c4e0c2a40055ab3d0f09654f730cce982"

[[override]]
  name = "github.com/juju/ratelimit"
  revision = "5b9ff866471762aa2ab2dced63c9fb6f53921342"

[[override]]
  name = "github.com/mailru/easyjson"
  revision = "d5b7844b561a7bc640052f1b935f7b800330d7e0"

[[override]]
  name = "github.com/pmezard/go-difflib"
  revision = "d8ed2627bdf02c080bf22230dbb337003b7aba2d"

[[override]]
  name = "github.com/spf13/pflag"
  revision = "9ff6c6923cfffbcd502984b8e0c80539a94968b7"

[[override]]
  name = "github.com/stretchr/testify"
  revision = "e3a8ff8ce36581f87a15341206f205b1da467059"

[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

[[override]]
  name =  "k8s.io/apimachinery"
  revision = "8a12651bddd061e6fac22c64db4fb0fe5b1013d2"
