#!/usr/bin/env bash
# vim: set syntax=sh:
set -e

if ! hash kubectl 2>/dev/null; then echo "Please install \`kubectl\` before running this command (https://kubernetes.io/docs/tasks/tools/install-kubectl/)"; exit 1; fi
if ! hash fzf 2>/dev/null; then echo "Please install \`fzf\` before running this command (https://github.com/junegunn/fzf#installation)"; exit 1; fi

selection=`kubectl get all --all-namespaces | grep -v 'NAMESPACE' | fzf --header "Select an object to describe..."`
namespace=`echo "$selection" | awk '{ print $1 }'`
object=`echo "$selection" | awk '{ print $2 }'`

kubectl -n $namespace describe $object
