#!/usr/bin/env bash
# vim: set syntax=sh:
set -e

resources="all
certificatesigningrequests
clusterrolebindings
clusterroles
clusters
componentstatuses
configmaps
controllerrevisions
cronjobs
daemonsets
deployments
endpoints
events
horizontalpodautoscalers
ingresses
jobs
limitranges
namespaces
networkpolicies
nodes
persistentvolumeclaims
persistentvolumes
poddisruptionbudgets
podpreset
pods
podsecuritypolicies
podtemplates
replicasets
replicationcontrollers
resourcequotas
rolebindings
roles
secrets
serviceaccounts
services
statefulsets
storageclasses
thirdpartyresources"

if ! hash kubectl 2>/dev/null; then echo "Please install \`kubectl\` before running this command (https://kubernetes.io/docs/tasks/tools/install-kubectl/)"; exit 1; fi
if ! hash fzf 2>/dev/null; then echo "Please install \`fzf\` before running this command (https://github.com/junegunn/fzf#installation)"; exit 1; fi

selected_resource=`echo "$resources" | fzf --header "Select a resource to describe..."`
selected_object=`kubectl get $selected_resource --all-namespaces | fzf --header "$selected_resource..." --header-lines=1`
selected_object_namespace=`echo "$selected_object" | awk '{ print $1 }'`
selected_object_name=`echo "$selected_object" | awk '{ print $2 }'`

kubectl -n $selected_object_namespace get $selected_resource $selected_object_name -o yaml "$@"
