#!/usr/bin/env bash
# vim: set syntax=sh:
set -e

if ! hash kubectl 2>/dev/null; then echo "Please install \`kubectl\` before running this command (https://kubernetes.io/docs/tasks/tools/install-kubectl/)"; exit 1; fi
if ! hash fzf 2>/dev/null; then echo "Please install \`fzf\` before running this command (https://github.com/junegunn/fzf#installation)"; exit 1; fi

selection=`kubectl get pods --all-namespaces | grep -v 'NAMESPACE' | fzf --header "Select a pod..."`
namespace=`echo "$selection" | awk '{ print $1 }'`
pod=`echo "$selection" | awk '{ print $2 }'`
podIP=`kubectl -n $namespace get pod $pod -o jsonpath="{range .status}{@.podIP}"`
nodeName=`kubectl -n $namespace get pod $pod -o jsonpath="{range .spec}{@.nodeName}"`

echo ssh $nodeName sudo apt-get install -y ngrep
ssh $nodeName sudo apt-get install -y ngrep

echo ssh $nodeName sudo ngrep -q -d flannel.1 host $podIP
ssh $nodeName sudo ngrep -q -d flannel.1 -t "$@" host $podIP
