#!/usr/bin/env bash
# vim: set syntax=sh:
set -e

if ! hash kubectl 2>/dev/null; then echo "Please install \`kubectl\` before running this command (https://kubernetes.io/docs/tasks/tools/install-kubectl/)"; exit 1; fi
if ! hash fzf 2>/dev/null; then echo "Please install \`fzf\` before running this command (https://github.com/junegunn/fzf#installation)"; exit 1; fi

if [ ! -z "$1" ] ; then
	kubectl config use-context "$1"
	exit $?
fi

selection=`kubectl config get-contexts | grep -v '^CURRENT' | tr '*' ' ' | fzf --header "Select a kube context..."`
context=`echo $selection | awk '{print $2}'`

kubectl config use-context $context
